version = "0.1.0"
readme = "README.md"

[tool.aerich]
tortoise_orm = "settings.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[project]
name = "fastapiminiproject"
version = "0.1.0"
dependencies = ["uvicorn>=0.35.0"]

[dependency-groups]
dev = [
    "aerich==0.7.1",
]
